FROM node:20-alpine

# Installer OpenSSL pour Prisma
RUN apk add --no-cache openssl

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer toutes les dépendances (dev incluses)
RUN npm install

# Exposer le port
EXPOSE 3000

# Générer Prisma et démarrer l'app
CMD sh -c "npx prisma generate && npm run start:dev:legacy"
